version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: empacotamento_api
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: development
      PORT: 3000
    volumes:
      - .:/usr/src/api
      - /usr/src/api/node_modules
    command: npm run dev
